
import React from 'react';
import { BrandPersona } from '../types';
import { Icons } from './Icons';
import PersonaCard from './PersonaCard';

interface ResultDashboardProps {
  data: BrandPersona;
  imageUrl: string | null;
  onReset: () => void;
}

const ResultDashboard: React.FC<ResultDashboardProps> = ({ data, imageUrl, onReset }) => {

  const handleExportDoc = () => {
    // Helper function to convert custom markdown-like syntax to Word-compatible HTML
    const formatForWord = (text: string) => {
      if (!text) return '';
      const lines = text.split('\n');
      let html = '';
      let inList = false;

      // Helper to bold text
      const parseBold = (str: string) => {
        return str.replace(/\*\*(.*?)\*\*/g, '<b>$1</b>');
      };

      lines.forEach(line => {
        const trimmed = line.trim();
        if (!trimmed) {
             if (inList) { html += '</ul>'; inList = false; }
             html += '<br/>'; 
             return; 
        }

        // Headers
        if (trimmed.startsWith('###')) {
           if (inList) { html += '</ul>'; inList = false; }
           html += `<h3>${trimmed.replace(/^###\s*/, '')}</h3>`;
        }
        // List Items
        else if (trimmed.startsWith('- ') || trimmed.startsWith('* ') || trimmed.startsWith('• ')) {
           if (!inList) { html += '<ul>'; inList = true; }
           html += `<li>${parseBold(trimmed.replace(/^[-*•]\s*/, ''))}</li>`;
        }
        // Numbered Items (treated as bold paragraphs for simplicity in Word or ordered list)
        else if (/^\d+\.\s/.test(trimmed)) {
            if (inList) { html += '</ul>'; inList = false; }
            const parts = trimmed.split(/(\d+\.\s)/);
            if(parts.length >= 2) {
               html += `<p><b>${parts[1]}</b>${parseBold(parts.slice(2).join(''))}</p>`;
            } else {
               html += `<p>${parseBold(trimmed)}</p>`;
            }
        }
        // Paragraphs
        else {
           if (inList) { html += '</ul>'; inList = false; }
           html += `<p>${parseBold(trimmed)}</p>`;
        }
      });

      if (inList) html += '</ul>';
      return html;
    };

    // Construct HTML content for the Word/Google Doc
    const content = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'>
        <title>${data.brandName} Brand Persona</title>
        <style>
          body { font-family: 'Malgun Gothic', sans-serif; line-height: 1.5; color: #333; }
          h1 { font-size: 28pt; color: #1e293b; border-bottom: 3px solid #4f46e5; padding-bottom: 15px; margin-bottom: 30px; }
          h2 { font-size: 20pt; color: #fff; background-color: #4f46e5; padding: 10px 15px; margin-top: 40px; margin-bottom: 20px; border-radius: 4px; }
          h3 { font-size: 14pt; color: #4338ca; margin-top: 25px; margin-bottom: 10px; border-left: 4px solid #4338ca; padding-left: 10px; }
          p { margin-bottom: 12px; font-size: 11pt; text-align: justify; }
          ul { margin-bottom: 15px; }
          li { margin-bottom: 5px; }
          b { color: #0f172a; }
          .tag { display: inline-block; background: #eef2ff; color: #4338ca; padding: 4px 10px; border-radius: 15px; font-size: 10pt; margin-right: 5px; border: 1px solid #c7d2fe; }
          .color-box { width: 50px; height: 20px; display: inline-block; border: 1px solid #ccc; margin-right: 10px; vertical-align: middle; }
          table { width: 100%; border-collapse: collapse; margin-top: 15px; }
          th, td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; }
          th { background-color: #f8fafc; color: #333; font-weight: bold; }
          .meta-info { font-size: 10pt; color: #64748b; margin-bottom: 40px; }
        </style>
      </head>
      <body>
        <h1>${data.brandName}</h1>
        <p class="meta-info">
          <strong>Slogan:</strong> ${data.slogan}<br/>
          <strong>Generated by:</strong> Brand Persona Architect
        </p>
        
        <h2>1. Identity & Strategy</h2>
        
        <h3>브랜드 철학</h3>
        ${formatForWord(data.philosophy)}
        
        <h3>핵심 전략</h3>
        ${formatForWord(data.coreStrategy)}
        
        <h3>핵심 기술/역량</h3>
        ${formatForWord(data.coreTechnology)}

        <h2>2. Market & Customer</h2>
        
        <h3>고객 정의 (Target)</h3>
        ${formatForWord(data.targetAudience)}
        
        <h3>Gen-Z 가치</h3>
        ${formatForWord(data.genZValue)}
        
        <h3>고객 문화 창조</h3>
        ${formatForWord(data.customerCulture)}

        <h2>3. Benefits & Value</h2>
        
        <h3>기능적 혜택 (Pain-Point)</h3>
        ${formatForWord(data.functionalBenefit)}
        
        <h3>경험적 혜택</h3>
        ${formatForWord(data.experientialBenefit)}
        
        <h3>상징적 혜택</h3>
        ${formatForWord(data.symbolicBenefit)}

        <h2>4. Positioning & Tone</h2>
        
        <h3>브랜드 멘트</h3>
        ${formatForWord(data.brandMent)}
        
        <h3>비교 우위 속성</h3>
        ${formatForWord(data.comparativeAdvantage)}

        <h3>품질 및 가격</h3>
        <p><b>품질 수준:</b></p>
        ${formatForWord(data.qualityLevel)}
        <p><b>가격 정책:</b></p>
        ${formatForWord(data.priceLevel)}

        <h2>5. Pomelli (Business DNA)</h2>
        
        <h3>Overview</h3>
        <p><b>Tagline:</b> "${data.pomelli.tagline}"</p>
        <p><b>Archetype:</b> ${data.pomelli.brandArchetype}</p>
        <p>${data.pomelli.businessOverview}</p>
        
        <h3>Visual Identity</h3>
        <p><b>Aesthetic Keywords:</b></p>
        <p>${data.pomelli.brandAesthetic.map(k => `<span class="tag">#${k}</span>`).join('')}</p>
        
        <p><b>Typography:</b> ${data.pomelli.typography}</p>
        
        <h4>Brand Colors</h4>
        <table>
          <tr><th>Color</th><th>Name / Hex</th><th>Description</th></tr>
          ${data.pomelli.colors.map(c => `
            <tr>
              <td><span class="color-box" style="background-color:${c.hex}"></span></td>
              <td><b>${c.name}</b><br/>${c.hex}</td>
              <td>${c.description}</td>
            </tr>
          `).join('')}
        </table>
        
        <h3>Tone & Values</h3>
        <p><b>Tone of Voice:</b> ${data.pomelli.toneOfVoice.join(', ')}</p>
        
        <h4>Core Values</h4>
        <ul>
          ${data.pomelli.brandValues.map(v => `<li><b>${v.title}:</b> ${v.description}</li>`).join('')}
        </ul>

      </body>
      </html>
    `;

    const blob = new Blob(['\ufeff', content], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${data.brandName.replace(/\s+/g, '_')}_Brand_Persona.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-7xl mx-auto pb-20">
      
      {/* Header Section */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
        <div>
          <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-2 flex items-center gap-3">
            {data.brandName}
            <span className="px-3 py-1 bg-indigo-100 text-indigo-700 text-sm font-bold rounded-full uppercase tracking-wider">Brand Identity</span>
          </h2>
          <p className="text-slate-500">{data.slogan}</p>
        </div>
        <div className="flex items-center gap-2">
            <button 
            onClick={handleExportDoc}
            className="flex items-center gap-2 px-5 py-3 bg-indigo-600 text-white rounded-xl hover:bg-indigo-700 transition-all font-bold shadow-md hover:shadow-lg active:scale-95"
            >
            <Icons.Download className="w-4 h-4" />
            리포트 다운로드
            </button>
            <button 
            onClick={onReset}
            className="flex items-center gap-2 px-5 py-3 bg-white border border-slate-200 text-slate-700 rounded-xl hover:bg-slate-50 hover:text-indigo-600 transition-colors font-medium shadow-sm"
            >
            <Icons.Repeat className="w-4 h-4" />
            새로 만들기
            </button>
        </div>
      </div>

      {/* Top Section: Image & Key Highlights */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
        {/* Image Card */}
        <div className="lg:col-span-1 bg-white rounded-2xl p-4 shadow-sm border border-slate-100 flex flex-col h-full">
          <div className="relative w-full aspect-square rounded-xl overflow-hidden bg-slate-100 mb-4 group">
             {imageUrl ? (
               <img src={imageUrl} alt="Brand Identity" className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" />
             ) : (
               <div className="w-full h-full flex items-center justify-center text-slate-400 flex-col gap-2">
                 <Icons.Sparkles className="w-10 h-10" />
                 <span>이미지 생성 실패</span>
               </div>
             )}
             <div className="absolute bottom-3 left-3 px-3 py-1 bg-black/60 backdrop-blur-md text-white text-xs rounded-full">
               Generated by Gemini Flash Image
             </div>
          </div>
          
          {data.brandNameSuggestions && data.brandNameSuggestions.length > 0 && (
             <div className="mt-auto">
               <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-3">추천 네이밍 후보</h4>
               <div className="flex flex-wrap gap-2">
                 {data.brandNameSuggestions.map((name, i) => (
                   <div key={i} className="flex-1 min-w-[100px] text-center px-3 py-2 bg-indigo-50 text-indigo-700 rounded-lg text-sm font-bold border border-indigo-100">
                     {name}
                   </div>
                 ))}
               </div>
             </div>
          )}
        </div>

        {/* Key Philosophy & Strategy */}
        <div className="lg:col-span-2 flex flex-col gap-6">
           <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <PersonaCard 
              title="브랜드 철학" 
              content={data.philosophy} 
              icon={Icons.Lightbulb} 
              colorClass="bg-amber-500"
              fullWidth={true}
            />
           </div>
           <div className="grid grid-cols-1 md:grid-cols-2 gap-6 flex-grow">
             <PersonaCard 
               title="핵심 전략" 
               content={data.coreStrategy} 
               icon={Icons.Target} 
               colorClass="bg-red-500"
             />
             <PersonaCard 
               title="핵심 기술/역량" 
               content={data.coreTechnology} 
               icon={Icons.Cpu} 
               colorClass="bg-blue-500"
             />
           </div>
        </div>
      </div>

      {/* Main Content Grid (Moved Up) */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
        
        {/* Column 1: Target & Culture */}
        <div className="space-y-6">
          <PersonaCard title="고객 정의 (Target)" content={data.targetAudience} icon={Icons.Users} colorClass="bg-emerald-500" />
          <PersonaCard title="Gen-Z 가치" content={data.genZValue} icon={Icons.Zap} colorClass="bg-yellow-500" />
          <PersonaCard title="고객 문화 창조" content={data.customerCulture} icon={Icons.Globe} colorClass="bg-cyan-500" />
          <PersonaCard title="고객 관리/멤버십" content={data.customerManagement} icon={Icons.Heart} colorClass="bg-pink-500" />
        </div>

        {/* Column 2: Positioning & Tone */}
        <div className="space-y-6">
          <PersonaCard title="브랜드 멘트 (Tone)" content={data.brandMent} icon={Icons.MessageCircle} colorClass="bg-violet-500" />
          <PersonaCard title="비교 우위 속성" content={data.comparativeAdvantage} icon={Icons.TrendingUp} colorClass="bg-orange-500" />
          <PersonaCard title="품질 수준" content={data.qualityLevel} icon={Icons.ShieldCheck} colorClass="bg-slate-700" />
          <PersonaCard title="가격 정책" content={data.priceLevel} icon={Icons.Tag} colorClass="bg-green-600" />
        </div>

        {/* Column 3: Benefits & Keywords */}
        <div className="space-y-6">
          <PersonaCard title="기능적 혜택 (Pain-Point)" content={data.functionalBenefit} icon={Icons.Briefcase} colorClass="bg-teal-500" />
          <PersonaCard title="경험적 혜택" content={data.experientialBenefit} icon={Icons.Smile} colorClass="bg-rose-500" />
          <PersonaCard title="상징적 혜택" content={data.symbolicBenefit} icon={Icons.Award} colorClass="bg-fuchsia-500" />
          <PersonaCard title="브랜드 키워드" content={data.keywords} icon={Icons.Layers} colorClass="bg-indigo-500" />
        </div>
      </div>

      {/* Pomelli Style: Brand DNA Section (Moved to Bottom) */}
      <div className="bg-white rounded-3xl p-6 md:p-8 shadow-md border border-slate-200 relative overflow-hidden">
        {/* Decorative Background */}
        <div className="absolute top-0 right-0 w-96 h-96 bg-fuchsia-50 rounded-full blur-3xl opacity-50 -mr-20 -mt-20 pointer-events-none"></div>
        <div className="absolute bottom-0 left-0 w-96 h-96 bg-indigo-50 rounded-full blur-3xl opacity-50 -ml-20 -mb-20 pointer-events-none"></div>

        {/* Header */}
        <div className="relative z-10 mb-10 border-b border-slate-100 pb-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="flex items-center gap-4">
                <div className="p-3 rounded-2xl bg-slate-900 text-white shadow-lg">
                    <Icons.Palette className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-2xl font-serif font-bold text-slate-900 tracking-tight">pomelli <span className="font-sans font-normal text-base text-slate-400">(Your Business DNA)</span></h3>
                  <p className="text-sm text-slate-500">Visual Identity & Core Strategy Overview</p>
                </div>
            </div>
            <div className="text-right">
                 <span className="inline-block px-3 py-1 bg-fuchsia-100 text-fuchsia-700 rounded-full text-xs font-bold uppercase tracking-wider mb-1">Archetype</span>
                 <p className="text-lg font-bold text-slate-800">{data.pomelli.brandArchetype || "The Creator"}</p>
            </div>
        </div>
        
        <div className="relative z-10">
           {/* Tagline & Overview */}
           <div className="text-center max-w-3xl mx-auto mb-12">
              <p className="text-3xl md:text-5xl font-serif italic text-slate-800 leading-tight mb-6">"{data.pomelli.tagline}"</p>
              <p className="text-slate-600 text-lg leading-relaxed">{data.pomelli.businessOverview}</p>
           </div>

           {/* DNA Grid */}
           <div className="grid grid-cols-1 md:grid-cols-12 gap-8">
              
              {/* Left: Visual Identity (Colors, Aesthetic, Typography) */}
              <div className="md:col-span-5 space-y-8">
                  
                  {/* Colors */}
                  <div>
                      <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                          <span className="w-2 h-2 rounded-full bg-slate-400"></span> Brand Colors
                      </h4>
                      <div className="space-y-3">
                          {data.pomelli.colors.map((color, idx) => (
                              <div key={idx} className="group flex items-center gap-4 bg-slate-50 p-3 rounded-xl border border-slate-100 hover:bg-white hover:shadow-md transition-all">
                                  <div 
                                      className="w-12 h-12 rounded-full shadow-inner border border-slate-200 flex-shrink-0 ring-2 ring-white"
                                      style={{ backgroundColor: color.hex }}
                                  ></div>
                                  <div className="min-w-0">
                                      <div className="flex items-center gap-2 mb-0.5">
                                        <p className="font-bold text-slate-800 text-sm">{color.name}</p>
                                        <span className="text-[10px] font-mono text-slate-400 bg-white px-1.5 rounded border border-slate-200">{color.hex}</span>
                                      </div>
                                      <p className="text-xs text-slate-500 truncate">{color.description}</p>
                                  </div>
                              </div>
                          ))}
                      </div>
                  </div>

                  {/* Aesthetic & Typography */}
                  <div className="grid grid-cols-1 gap-6">
                     <div className="bg-slate-50 rounded-2xl p-5 border border-slate-100">
                        <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">Brand Aesthetic</h4>
                        <div className="flex flex-wrap gap-2">
                            {data.pomelli.brandAesthetic?.map((keyword, idx) => (
                                <span key={idx} className="px-3 py-1.5 bg-white text-slate-700 border border-slate-200 rounded-lg text-xs font-medium shadow-sm">
                                    #{keyword}
                                </span>
                            )) || <span className="text-xs text-slate-400">Not specified</span>}
                        </div>
                     </div>

                     <div className="bg-slate-50 rounded-2xl p-5 border border-slate-100">
                        <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">Typography</h4>
                        <p className="text-sm text-slate-700 font-medium">{data.pomelli.typography}</p>
                     </div>
                  </div>
              </div>

              {/* Right: Values & Tone */}
              <div className="md:col-span-7 space-y-8">
                  
                  {/* Tone of Voice */}
                  <div>
                     <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                          <span className="w-2 h-2 rounded-full bg-slate-400"></span> Tone of Voice
                      </h4>
                      <div className="flex flex-wrap gap-3">
                          {data.pomelli.toneOfVoice?.map((tone, idx) => (
                              <div key={idx} className="px-4 py-2 bg-indigo-50 text-indigo-700 rounded-full text-sm font-bold">
                                  {tone}
                              </div>
                          )) || <span className="text-sm text-slate-400">Professional, Trustworthy</span>}
                      </div>
                  </div>

                  {/* Core Values */}
                  <div>
                      <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                          <span className="w-2 h-2 rounded-full bg-slate-400"></span> Core Values
                      </h4>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                          {data.pomelli.brandValues.map((val, idx) => (
                              <div key={idx} className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm hover:border-indigo-100 transition-colors">
                                  <div className="w-8 h-8 rounded-lg bg-slate-900 text-white flex items-center justify-center text-xs font-bold mb-3">
                                    0{idx + 1}
                                  </div>
                                  <p className="font-bold text-slate-800 mb-2">{val.title}</p>
                                  <p className="text-xs text-slate-500 leading-relaxed">{val.description}</p>
                              </div>
                          ))}
                      </div>
                  </div>

              </div>
           </div>
        </div>
      </div>

    </div>
  );
};

export default ResultDashboard;
